import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNav from "@/components/navbar/ResponsiveNav";

export const metadata: Metadata = {
  title: "Hridoy Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ResponsiveNav/>
        {children}
        
        </body>
    </html>
  );
}
